-- CreateEnum
CREATE TYPE "ORDER_STATUS" AS ENUM ('PAID', 'UNPAID');

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "paidAmount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "remainingAmount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "status" "ORDER_STATUS" NOT NULL DEFAULT E'UNPAID';

-- AlterTable
ALTER TABLE "OrderItems" ADD COLUMN     "note" TEXT;
